<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\TestPlatform.Application\TestPlatform.Application.csproj" />
      <ProjectReference Include="..\TestPlatform.Core\TestPlatform.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.3" />
    </ItemGroup>

</Project>
