// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestPlatform.Infrastructure.Postgres;

#nullable disable

namespace TestPlatform.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(TestPlatformDbContext))]
    [Migration("20260714230924_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("question_tags", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Attempts.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalMaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Type", "SourceId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Status");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ImageName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Questions.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name_lower_unique");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Tests.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TabNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.HasIndex("TabNumber")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.HasOne("TestPlatform.Core.Questions.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestPlatform.Core.Questions.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestPlatform.Core.Attempts.Attempt", b =>
                {
                    b.OwnsMany("TestPlatform.Core.Attempts.AttemptAnswer", "AttemptAnswers", b1 =>
                        {
                            b1.Property<Guid>("AttemptId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("MatchingPairs")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<decimal?>("NumberAnswer")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<string>("SelectedOptionIds")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("TextAnswer")
                                .HasColumnType("text");

                            b1.HasKey("AttemptId", "QuestionId");

                            b1.HasIndex("AttemptId", "QuestionId")
                                .IsUnique();

                            b1.ToTable("attempt_answers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AttemptId");
                        });

                    b.OwnsOne("TestPlatform.Core.Attempts.AttemptResult", "AttemptResult", b1 =>
                        {
                            b1.Property<Guid>("AttemptId");

                            b1.Property<int>("CorrectAnswers");

                            b1.Property<decimal>("EarnedPoints");

                            b1.HasKey("AttemptId");

                            b1.ToTable("attempts");

                            b1
                                .ToJson("AttemptResult")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AttemptId");
                        });

                    b.Navigation("AttemptAnswers");

                    b.Navigation("AttemptResult");
                });

            modelBuilder.Entity("TestPlatform.Core.Exams.Exam", b =>
                {
                    b.OwnsMany("TestPlatform.Core.Shared.QuestionAssignment", "Questions", b1 =>
                        {
                            b1.Property<Guid>("ExamId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("ExamId", "QuestionId");

                            b1.HasIndex("ExamId", "Order")
                                .IsUnique();

                            b1.HasIndex("ExamId", "QuestionId")
                                .IsUnique();

                            b1.ToTable("exam_questions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExamId");
                        });

                    b.OwnsOne("TestPlatform.Core.Exams.ExamPassingRule", "PassingRule", b1 =>
                        {
                            b1.Property<Guid>("ExamId");

                            b1.HasKey("ExamId");

                            b1.ToTable("exams");

                            b1
                                .ToJson("PassingRule")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExamId");
                        });

                    b.OwnsOne("TestPlatform.Core.Exams.ExamSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ExamId");

                            b1.HasKey("ExamId");

                            b1.ToTable("exams");

                            b1
                                .ToJson("Schedule")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExamId");
                        });

                    b.Navigation("PassingRule");

                    b.Navigation("Questions");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("TestPlatform.Core.Tests.Test", b =>
                {
                    b.OwnsMany("TestPlatform.Core.Shared.QuestionAssignment", "Questions", b1 =>
                        {
                            b1.Property<Guid>("TestId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<int>("Score")
                                .HasColumnType("integer");

                            b1.HasKey("TestId", "QuestionId");

                            b1.HasIndex("TestId", "Order")
                                .IsUnique();

                            b1.HasIndex("TestId", "QuestionId")
                                .IsUnique();

                            b1.ToTable("test_questions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TestId");
                        });

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}

