// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestPlatform.Infrastructure.Postgres;

#nullable disable

namespace TestPlatform.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(TestPlatformDbContext))]
    [Migration("20260722215224_NormalizeTagNames")]
    partial class NormalizeTagNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("question_tags", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Attempts.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LatestFinishAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MinPassingPercent")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("MinPassingScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewAvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalMaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RequestId")
                        .IsUnique();

                    b.HasIndex("UserId", "StartedAt");

                    b.HasIndex("Type", "SourceId", "StartedAt");

                    b.HasIndex("UserId", "Type", "SourceId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptsLimit")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Status");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Files.FileAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AttachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId", "Status");

                    b.ToTable("file_assets", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerDefinition")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Content", "TestPlatform.Core.Questions.Question.Content#QuestionContent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Explanation")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Explanation");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Text");
                        });

                    b.HasKey("Id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Questions.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_normalized_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Tests.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("TestPlatform.Core.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TabNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.HasIndex("TabNumber")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("QuestionTag", b =>
                {
                    b.HasOne("TestPlatform.Core.Questions.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestPlatform.Core.Questions.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestPlatform.Core.Attempts.Attempt", b =>
                {
                    b.OwnsMany("TestPlatform.Core.Attempts.AttemptAnswer", "AttemptAnswers", b1 =>
                        {
                            b1.Property<Guid>("AttemptId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("MatchingPairs")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<decimal?>("NumberAnswer")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<string>("SelectedOptionIds")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("TextAnswer")
                                .HasColumnType("text");

                            b1.HasKey("AttemptId", "QuestionId");

                            b1.HasIndex("AttemptId", "QuestionId")
                                .IsUnique();

                            b1.ToTable("attempt_answers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AttemptId");
                        });

                    b.OwnsMany("TestPlatform.Core.Attempts.AttemptQuestionSelection", "QuestionSelections", b1 =>
                        {
                            b1.Property<Guid>("AttemptId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Score")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.HasKey("AttemptId", "QuestionId");

                            b1.HasIndex("QuestionId");

                            b1.ToTable("attempt_questions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AttemptId");

                            b1.HasOne("TestPlatform.Core.Questions.Question", null)
                                .WithMany()
                                .HasForeignKey("QuestionId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("TestPlatform.Core.Attempts.AttemptResult", "AttemptResult", b1 =>
                        {
                            b1.Property<Guid>("AttemptId");

                            b1.Property<int>("CorrectAnswers");

                            b1.Property<decimal>("EarnedPoints");

                            b1.Property<bool?>("Passed");

                            b1.HasKey("AttemptId");

                            b1.ToTable("attempts");

                            b1
                                .ToJson("AttemptResult")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AttemptId");
                        });

                    b.Navigation("AttemptAnswers");

                    b.Navigation("AttemptResult");

                    b.Navigation("QuestionSelections");
                });

            modelBuilder.Entity("TestPlatform.Core.Exams.Exam", b =>
                {
                    b.OwnsOne("TestPlatform.Core.Exams.ExamPassingRule", "PassingRule", b1 =>
                        {
                            b1.Property<Guid>("ExamId");

                            b1.HasKey("ExamId");

                            b1.ToTable("exams");

                            b1
                                .ToJson("PassingRule")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExamId");
                        });

                    b.OwnsOne("TestPlatform.Core.Exams.ExamSchedule", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("ExamId");

                            b1.HasKey("ExamId");

                            b1.ToTable("exams");

                            b1
                                .ToJson("Schedule")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExamId");
                        });

                    b.OwnsMany("TestPlatform.Core.Exams.ExamSection", "Sections", b1 =>
                        {
                            b1.Property<Guid>("ExamId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<int>("QuestionsToSelect")
                                .HasColumnType("integer");

                            b1.Property<int>("ScorePerQuestion")
                                .HasColumnType("integer");

                            b1.HasKey("ExamId", "Id");

                            b1.ToTable("exam_sections", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ExamId");

                            b1.OwnsMany("TestPlatform.Core.Exams.ExamSectionQuestion", "Questions", b2 =>
                                {
                                    b2.Property<Guid>("ExamId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("SectionId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("QuestionId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("ExamId", "SectionId", "QuestionId");

                                    b2.HasIndex("QuestionId");

                                    b2.ToTable("exam_section_questions", (string)null);

                                    b2.HasOne("TestPlatform.Core.Questions.Question", null)
                                        .WithMany()
                                        .HasForeignKey("QuestionId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("ExamId", "SectionId");
                                });

                            b1.Navigation("Questions");
                        });

                    b.Navigation("PassingRule");

                    b.Navigation("Schedule");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("TestPlatform.Core.Tests.Test", b =>
                {
                    b.OwnsMany("TestPlatform.Core.Tests.TestQuestion", "Questions", b1 =>
                        {
                            b1.Property<Guid>("TestId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Order")
                                .HasColumnType("integer");

                            b1.HasKey("TestId", "QuestionId");

                            b1.HasIndex("QuestionId");

                            b1.HasIndex("TestId", "Order")
                                .IsUnique();

                            b1.HasIndex("TestId", "QuestionId")
                                .IsUnique();

                            b1.ToTable("test_questions", (string)null);

                            b1.HasOne("TestPlatform.Core.Questions.Question", null)
                                .WithMany()
                                .HasForeignKey("QuestionId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TestId");
                        });

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
