version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: testPlatformDb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: testplatform_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5062:5062"   # HTTP
      - "7257:7257"   # HTTPS
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5062;https://+:7257"
      ConnectionStrings__TestPlatformContextPostgreSQL: "Host=postgres;Port=5432;Database=testPlatformDb;Username=postgres;Password=123456789"
    volumes:
      - images_data:/app/wwwroot/images
      
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.6
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    volumes:
      - ./containers/identity:/opt/keycloak/data
      - ./containers/identity/themes:/opt/keycloak/themes
    ports:
      - "8080:8080"
      - "9000:9000"
    user: root #development only
    
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: testplatform_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
  
  filebrowser:
    image: filebrowser/filebrowser:s6
    ports:
      - "8090:80"
    volumes:
      - images_data:/srv
      - filebrowser_db:/database
    environment:
      - PUID=1000
      - PGID=1000
      - FB_DATABASE=/database/filebrowser.db

volumes:
  pgdata:
  pgadmin_data:
  filebrowser_db:
  images_data:
