<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TestPlatform.Application\TestPlatform.Application.csproj" />
      <ProjectReference Include="..\TestPlatform.Core\TestPlatform.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.1.5" />
      <PackageReference Update="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
    </ItemGroup>

</Project>
