import { Plus, Trash2 } from 'lucide-react'
import type { Dispatch, SetStateAction } from 'react'

export type ChoiceOption = { text: string; isCorrect: boolean; imageId?: string | null; previewUrl?: string | null }
export type MatchPair = { leftId: string; left: string; leftImageId?: string | null; rightId: string; right: string; rightImageId?: string | null }

export function ChoiceFields({ choiceMode, onModeChange, options, setOptions, onSetCorrect, onUploadImage, uploadingImage }: { choiceMode: 'single' | 'multiple'; onModeChange: (value: 'single' | 'multiple') => void; options: ChoiceOption[]; setOptions: Dispatch<SetStateAction<ChoiceOption[]>>; onSetCorrect: (index: number, checked: boolean) => void; onUploadImage: (index: number, file: File) => Promise<void>; uploadingImage: boolean }) {
  return <fieldset className="mt-5"><div className="flex items-end justify-between gap-3"><label className="label">Режим выбора<select className="input mt-2" onChange={(event) => onModeChange(event.target.value as 'single' | 'multiple')} value={choiceMode}><option value="single">Один ответ</option><option value="multiple">Несколько ответов</option></select></label><button className="button-secondary" onClick={() => setOptions((current) => [...current, { text: '', isCorrect: false }])} type="button"><Plus size={16} /> Вариант</button></div><div className="mt-3 space-y-3">{options.map((option, index) => <div className="rounded-lg border border-slate-200 p-3" key={index}><div className="flex items-center gap-2"><input checked={option.isCorrect} name="correct-option" onChange={(event) => onSetCorrect(index, event.target.checked)} type={choiceMode === 'single' ? 'radio' : 'checkbox'} /><input className="input" onChange={(event) => setOptions((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item))} placeholder={`Вариант ${index + 1}`} required value={option.text} /><button className="icon-button text-rose-600" disabled={options.length <= 2} onClick={() => setOptions((current) => current.filter((_, itemIndex) => itemIndex !== index))} type="button"><Trash2 size={16} /></button></div><div className="mt-3 flex items-center gap-3 pl-6">{option.previewUrl && <img alt={`Изображение варианта ${index + 1}`} className="size-12 rounded-lg object-cover" src={option.previewUrl} />}<label className="cursor-pointer text-sm font-medium text-indigo-700 hover:text-indigo-900">{option.previewUrl ? 'Заменить изображение' : 'Добавить изображение'}<input accept="image/*" className="sr-only" disabled={uploadingImage} onChange={(event) => { const file = event.target.files?.[0]; if (file) void onUploadImage(index, file) }} type="file" /></label>{option.imageId && <button className="text-sm text-rose-600" onClick={() => setOptions((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, imageId: null, previewUrl: null } : item))} type="button">Удалить изображение</button>}</div></div>)}</div></fieldset>
}

export function MatchingFields({ pairs, setPairs }: { pairs: MatchPair[]; setPairs: Dispatch<SetStateAction<MatchPair[]>> }) {
  return <fieldset className="mt-5"><div className="flex items-center justify-between"><legend className="label">Правильные пары</legend><button className="button-secondary" onClick={() => setPairs((current) => [...current, newPair()])} type="button"><Plus size={16} /> Пара</button></div><div className="mt-3 space-y-2">{pairs.map((pair, index) => <div className="grid grid-cols-[1fr_auto_1fr_auto] items-center gap-2" key={pair.leftId}><input className="input" onChange={(event) => setPairs((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, left: event.target.value } : item))} placeholder="Левая часть" required value={pair.left} /><span className="text-slate-400">→</span><input className="input" onChange={(event) => setPairs((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, right: event.target.value } : item))} placeholder="Правая часть" required value={pair.right} /><button className="icon-button text-rose-600" disabled={pairs.length <= 1} onClick={() => setPairs((current) => current.filter((_, itemIndex) => itemIndex !== index))} type="button"><Trash2 size={16} /></button></div>)}</div></fieldset>
}

export function newPair(): MatchPair { return { leftId: crypto.randomUUID(), left: '', rightId: crypto.randomUUID(), right: '' } }
