import { ImagePlus } from 'lucide-react'
import type { ExamDetails } from '@/entities/exam'
import type { ExamSettingsPanelProps } from './ExamSettingsPanel'

export function ExamInfoCard({ exam }: { exam: ExamDetails }) {
  return <div className="card order-first"><h2 className="text-lg font-semibold">Информация</h2><dl className="mt-4 divide-y divide-slate-100 text-sm"><Row label="Статус" value={exam.status} /><Row label="Секций" value={String(exam.sections.length)} /><Row label="Вопросов" value={String(exam.totalQuestions)} /><Row label="Макс. балл" value={String(exam.totalMaxScore)} /><Row label="ID" value={exam.id} /></dl></div>
}

export function ExamCoverCard({ editable, busy, coverUrl, onRemove, onUpload }: { editable: boolean; busy: boolean; coverUrl?: string; onRemove: () => Promise<void>; onUpload: (file: File) => Promise<void> }) {
  return <div className="card"><h2 className="text-lg font-semibold">Обложка</h2><div className="mt-5">{coverUrl ? <><img alt="Обложка экзамена" className="max-h-64 w-full rounded-xl bg-slate-50 object-contain" src={coverUrl} />{editable && <button className="button-secondary mt-3 w-full text-rose-600" disabled={busy} onClick={() => void onRemove()} type="button">Удалить обложку</button>}</> : editable ? <label className="flex cursor-pointer flex-col items-center gap-2 rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-10 text-sm text-slate-600 hover:bg-slate-100"><ImagePlus size={24} />Загрузить изображение<input accept="image/*" className="sr-only" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; if (file) void onUpload(file) }} type="file" /></label> : <p className="text-sm text-slate-500">Обложка не задана</p>}</div></div>
}

export function ExamPassingRuleCard({ exam, editable, busy, type, value, onChangeType, onChangeValue, onSave }: { exam: ExamDetails; editable: boolean; busy: boolean; type: 'score' | 'percent'; value: string; onChangeType: (value: 'score' | 'percent') => void; onChangeValue: (value: string) => void; onSave: () => Promise<void> }) {
  const current = exam.passingRule?.minPercent != null ? `Не менее ${exam.passingRule.minPercent}%` : exam.passingRule?.minScore != null ? `Не менее ${exam.passingRule.minScore} баллов` : 'Не задано'
  return <div className="card"><h2 className="text-lg font-semibold">Правило прохождения</h2><p className="mt-1 text-sm text-slate-500">Укажите минимальный результат для успешного прохождения экзамена.</p>{editable ? <div className="mt-5 space-y-3"><select className="input" disabled={busy} onChange={(event) => onChangeType(event.target.value as 'score' | 'percent')} value={type}><option value="score">Минимальный балл</option><option value="percent">Минимальный процент</option></select><input className="input" disabled={busy} max={type === 'percent' ? 100 : exam.totalMaxScore} min="1" onChange={(event) => onChangeValue(event.target.value)} placeholder={type === 'percent' ? 'Например, 70' : 'Например, 20'} type="number" value={value} /><button className="hidden" disabled={busy || !value || Number(value) <= 0} onClick={() => void onSave()} type="button">Сохранить правило</button></div> : <dl className="mt-4 divide-y divide-slate-100 text-sm"><Row label="Условие" value={current} /></dl>}</div>
}

export function ExamRestrictionsCard(props: ExamSettingsPanelProps) {
  const { editable, busy, hasTimeLimit, timeLimit, availableFrom, availableTo, attemptsLimit, reviewPolicy } = props
  return <div className="card"><h2 className="text-lg font-semibold">Ограничения</h2><label className="mt-4 flex items-center gap-3 text-sm"><input checked={hasTimeLimit} disabled={!editable || busy} onChange={(event) => void props.onToggleTimeLimit(event.target.checked)} type="checkbox" /> Ограничить время</label>{hasTimeLimit && <div className="mt-4 flex gap-2"><input className="input" disabled={!editable} min="2" onChange={(event) => props.setTimeLimit(event.target.value)} type="number" value={timeLimit} />{editable && <button className="hidden" disabled={busy || Number(timeLimit) < 2} onClick={() => void props.onSaveTimeLimit()} type="button">Сохранить</button>}</div>}
    <div className="mt-6 border-t border-slate-100 pt-5"><h3 className="font-medium">Период доступности</h3><p className="mt-1 text-xs text-slate-500">Когда экзамен можно начать проходить.</p><div className="mt-4 grid gap-3"><DateField disabled={!editable || busy} label="Доступен с" onChange={props.setAvailableFrom} value={availableFrom} /><DateField disabled={!editable || busy} label="Доступен до" min={availableFrom || undefined} onChange={props.setAvailableTo} value={availableTo} /></div>{editable && <button className="hidden" disabled={busy || Boolean(availableFrom && availableTo && availableFrom >= availableTo)} onClick={() => void props.onSaveSchedule()} type="button">Сохранить период</button>}</div>
    <label className="label mt-5">Количество попыток<input className="input mt-2" disabled={!editable} min="1" onChange={(event) => props.setAttemptsLimit(event.target.value)} type="number" value={attemptsLimit} /></label><label className="label mt-5">Правило просмотра<select className="input mt-2" disabled={!editable || busy} onChange={(event) => props.setReviewPolicy(event.target.value as 'Immediately' | 'AfterExamClosed')} value={reviewPolicy}><option value="Immediately">Сразу после завершения</option><option value="AfterExamClosed">После окончания экзамена</option></select></label>{editable && <button className="hidden" disabled={busy || Number(attemptsLimit) < 1} onClick={() => void props.onSaveAttempts()} type="button">Сохранить настройки</button>}
  </div>
}

function DateField({ label, value, disabled, min, onChange }: { label: string; value: string; disabled: boolean; min?: string; onChange: (value: string) => void }) { return <label className="label">{label}<input className="input mt-2" disabled={disabled} min={min} onChange={(event) => onChange(event.target.value)} type="datetime-local" value={value} /></label> }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 py-3"><dt className="text-slate-500">{label}</dt><dd className="text-right font-medium">{value}</dd></div> }
